name: CI

on:
  pull_request:
    branches: [master, core]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        run: pnpm test
