name: Test

on:
  pull_request:
    branches: [main, v3]

jobs:
  test:
    name: Test (${{matrix.os}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Master
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build All
        run: pnpm build:all

      - name: Test
        run: pnpm test

      - name: Clean
        run: pnpm clean

      - name: Type Check
        run: pnpm types:check
